GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/604e112fa6921e12aa37fa04

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "AAA",
    "subscribedToChannel" : "adasdasd"
}